[[plugins]]
repo = 'ervandew/supertab'
[[plugins]]
repo = 'preservim/vim-indent-guides'
[[plugins]]
repo = 'ctrlpvim/ctrlp.vim'
[[plugins]]
repo = 'neomake/neomake'
[[plugins]]
repo = 'vim-airline/vim-airline'
[[plugins]]
repo = 'vim-airline/vim-airline-themes'
[[plugins]]
repo = 'ryanoasis/vim-devicons'
